name: Docker Images CI

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Extract service info from docker-compose.yml
        id: extract
        run: |
          echo "services_json<<EOF" >> $GITHUB_ENV
          yq eval '.services[] | {"context": .build.context, "image": .image}' docker-compose.yml -o=json | jq -c '.' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Build and push images
        run: |
          echo "${{ env.services_json }}" | while read -r service; do
            context=$(echo $service | jq -r '.context')
            image_name=$(echo $service | jq -r '.image')
            
            # 提取镜像标签
            tag=$(echo $image_name | cut -d':' -f2)
            
            echo "Building and pushing image from context: $context with tag: $tag"
            
            # 使用 docker buildx 构建并推送
            docker buildx build \
              --platform linux/amd64 \
              --push \
              -t ${{ secrets.DOCKERHUB_USERNAME }}/hellossrf:$tag \
              $context
          done
